# Generated by Django 3.2 on 2021-08-09 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dim_coffee',
            fields=[
                ('coffee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('roaster', models.CharField(max_length=100)),
                ('farmer', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('varietals', models.CharField(max_length=100, null=True)),
                ('process', models.CharField(choices=[('WA', 'Washed'), ('NA', 'Natural'), ('EA', 'EA Decaf'), ('SW', 'Swiss Water Decaf')], max_length=2, null=True)),
                ('elevation', models.IntegerField(null=True)),
                ('roaster_notes', models.TextField(default='', max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('brew_method', models.CharField(choices=[('V', 'V60'), ('CX', 'Chemex'), ('KA', 'Kalita Wave'), ('CR', 'Clover'), ('AP', 'AeroPress'), ('FP', 'French Press')], max_length=2, null=True)),
                ('tasting_notes', models.TextField(max_length=4000, null=True)),
                ('rating', models.IntegerField(choices=[(1, 'No'), (2, 'Tolerable'), (3, 'Good'), (4, 'Like'), (5, 'Love')])),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('coffee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coffees.dim_coffee')),
                ('updated_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
