# Generated by Django 3.2 on 2021-08-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='updated_by',
            new_name='user_id',
        ),
    ]
