# Generated by Django 3.2.5 on 2021-07-28 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee_details',
            name='roaster_notes',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='coffee_ratings',
            name='updated_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
