# Generated by Django 3.2.5 on 2021-07-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210728_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee_details',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coffee_details',
            name='elevation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee_details',
            name='process',
            field=models.CharField(choices=[('WA', 'Washed'), ('NA', 'Natural'), ('EA', 'EA Decaf'), ('SW', 'Swiss Water Decaf')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='coffee_details',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coffee_details',
            name='roaster_notes',
            field=models.TextField(default='', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='coffee_ratings',
            name='brew_method',
            field=models.CharField(choices=[('V', 'V60'), ('CX', 'Chemex'), ('KA', 'Kalita Wave'), ('CR', 'Clover'), ('AP', 'AeroPress'), ('FP', 'French Press')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='coffee_ratings',
            name='tasting_notes',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
