# Generated by Django 3.2 on 2021-08-14 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dim_coffee',
            fields=[
                ('coffee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('farmer', models.CharField(max_length=50, null=True)),
                ('process', models.CharField(choices=[('WA', 'Washed'), ('NA', 'Natural'), ('EA', 'EA Decaf'), ('SW', 'Swiss Water Decaf')], max_length=2, null=True)),
                ('elevation', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dim_country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('country_code_alpha', models.CharField(max_length=2, null=True)),
                ('country_code_alpha3', models.CharField(max_length=3, null=True)),
                ('name_long', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dim_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_notes', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dim_roaster',
            fields=[
                ('roaster_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dim_varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('brew_method', models.CharField(choices=[('V', 'V60'), ('CX', 'Chemex'), ('KA', 'Kalita Wave'), ('CR', 'Clover'), ('AP', 'AeroPress'), ('FP', 'French Press')], max_length=2, null=True)),
                ('reaction', models.TextField(max_length=500, null=True)),
                ('acidity', models.IntegerField(choices=[], null=True)),
                ('sweetness', models.IntegerField(choices=[], null=True)),
                ('complexity', models.IntegerField(choices=[], null=True)),
                ('balance', models.IntegerField(choices=[], null=True)),
                ('rating', models.IntegerField(choices=[(1, 'No'), (2, 'Tolerable'), (3, 'Good'), (4, 'Like'), (5, 'Love')], null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('coffee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coffee.dim_coffee')),
                ('user_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dim_coffee',
            name='country_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coffee.dim_country', to_field='country_code'),
        ),
        migrations.AddField(
            model_name='dim_coffee',
            name='roaster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coffee.dim_roaster'),
        ),
        migrations.AddField(
            model_name='dim_coffee',
            name='roaster_notes',
            field=models.ManyToManyField(to='coffee.dim_notes'),
        ),
        migrations.AddField(
            model_name='dim_coffee',
            name='varietals',
            field=models.ManyToManyField(to='coffee.dim_varietal'),
        ),
    ]
