# Generated by Django 3.2 on 2021-08-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20210814_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_coffee',
            name='roaster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coffees', to='coffee.dim_roaster'),
        ),
    ]
