# Generated by Django 3.2 on 2021-08-15 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_auto_20210815_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dim_coffee',
            old_name='country_code',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='dim_coffee',
            old_name='roaster_id',
            new_name='roaster',
        ),
    ]
