# Generated by Django 3.2 on 2021-08-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_auto_20210815_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='coffee_id',
            new_name='coffee',
        ),
    ]
