# Generated by Django 3.2 on 2021-08-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_rename_coffee_id_ratings_coffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='acidity',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Tolerable'), (3, 'Good'), (4, 'Like'), (5, 'Love')], null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='balance',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Tolerable'), (3, 'Good'), (4, 'Like'), (5, 'Love')], null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='coffee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='coffee.dim_coffee'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='complexity',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Tolerable'), (3, 'Good'), (4, 'Like'), (5, 'Love')], null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='sweetness',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Tolerable'), (3, 'Good'), (4, 'Like'), (5, 'Love')], null=True),
        ),
    ]
