# Generated by Django 3.2 on 2021-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_auto_20210817_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_coffee',
            name='process',
            field=models.CharField(choices=[('Washed', 'Washed'), ('Natural', 'Natural'), ('EA Decaf', 'EA Decaf'), ('Swiss Water Decaf', 'Swiss Water Decaf')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='brew_method',
            field=models.CharField(choices=[('V60', 'V60'), ('Chemex', 'Chemex'), ('Kalita Wave', 'Kalita Wave'), ('Clover', 'Clover'), ('AeroPress', 'AeroPress'), ('French Press', 'French Press')], max_length=25, null=True),
        ),
    ]
