# Generated by Django 3.2 on 2021-08-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_auto_20210817_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='dim_coffee',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='dim_notes',
            options={'ordering': ['flavor_notes']},
        ),
        migrations.AlterModelOptions(
            name='dim_roaster',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='dim_varietal',
            options={'ordering': ['varietal']},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'ordering': ['-last_updated']},
        ),
    ]
