# Generated by Django 3.2 on 2021-08-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_auto_20210818_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_coffee',
            name='process',
            field=models.CharField(choices=[('Washed', 'Washed'), ('Natural', 'Natural'), ('Pulp Natural', 'Pulp Natural'), ('Honey', 'Honey'), ('Yellow Honey', 'Yellow Honey'), ('Honey Washed', 'Honey Washed'), ('Honey Natural', 'Honey Natural'), ('EA Decaf', 'EA Decaf'), ('Swiss Water Decaf', 'Swiss Water Decaf')], max_length=20, null=True),
        ),
    ]
