# Generated by Django 3.2 on 2021-08-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0012_auto_20210818_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_coffee',
            name='elevation',
            field=models.IntegerField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='brew_method',
            field=models.CharField(choices=[('V60', 'V60'), ('Chemex', 'Chemex'), ('Kalita Wave', 'Kalita Wave'), ('Clover', 'Clover'), ('AeroPress', 'AeroPress'), ('French Press', 'French Press'), ('Drip', 'Drip'), ('Cupping', 'Cupping'), ('Siphon', 'Siphon')], max_length=25, null=True),
        ),
    ]
