# Generated by Django 3.2 on 2021-08-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_auto_20210818_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_coffee',
            name='roaster_notes',
            field=models.ManyToManyField(related_name='notes', to='coffee.dim_notes'),
        ),
    ]
