# Generated by Django 3.2 on 2021-08-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0015_auto_20210820_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name_long',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dim_coffee',
            name='farmer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dim_coffee',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dim_notes',
            name='flavor_notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dim_roaster',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dim_varietal',
            name='varietal',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
