# Generated by Django 3.2 on 2021-08-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0018_auto_20210823_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='coffee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', related_query_name='ratings', to='coffee.dim_coffee'),
        ),
    ]
