# Generated by Django 3.2 on 2021-08-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0020_ratings_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_coffee',
            name='varietals',
            field=models.ManyToManyField(blank=True, related_name='varieties', to='coffee.dim_varietal'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_date',
            field=models.DateField(null=True),
        ),
    ]
