# Generated by Django 3.2 on 2021-08-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0022_alter_dim_coffee_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='brew_method',
            field=models.CharField(choices=[('V60', 'V60'), ('Chemex', 'Chemex'), ('Kalita Wave', 'Kalita Wave'), ('Clover', 'Clover'), ('AeroPress', 'AeroPress'), ('French Press', 'French Press'), ('Drip', 'Drip'), ('Cupping', 'Cupping'), ('Siphon', 'Siphon'), ('Espresso', 'Espresso')], max_length=25, null=True),
        ),
    ]
