# Generated by Django 3.2 on 2021-09-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0024_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
