# Generated by Django 3.2.5 on 2021-07-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffee_details',
            fields=[
                ('coffee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('roaster', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('process', models.CharField(choices=[('WA', 'Washed'), ('NA', 'Natrual'), ('EA', 'EA Decaf'), ('SW', 'Swiss Water Decaf')], max_length=2)),
                ('elevation', models.IntegerField()),
                ('tasting_notes', models.TextField(max_length=4000)),
                ('rating', models.IntegerField(choices=[(1, 'No'), (2, 'Tolerable'), (3, 'Good'), (4, 'Like'), (5, 'Love')])),
            ],
        ),
    ]
