# Generated by Django 3.2.5 on 2021-07-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_details',
            name='farmer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coffee_details',
            name='varietals',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
